ruleset(name="local2forwarder") {
    action(
        type="omfwd"
        target="192.168.0.9"
        port="514"
        protocol="tcp"
        action.resumeRetryCount="-1"
        queue.type="linkedList"
        queue.filename="lfqueue"
        queue.maxDiskSpace="1g"
        queue.saveOnShutdown="on"
    )
}
